cosmic:
    host: 'sftp-cancer.sanger.ac.uk'
    cosmic_version: 'v83'
    ref_genome_version: GRCh37

dbsnp_url: 'ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606_b150_GRCh37p13/VCF/common_all_20170710.vcf.gz'

genetic_map_txt_url: 'https://data.broadinstitute.org/alkesgroup/Eagle/downloads/tables/genetic_map_hg19_withX.txt.gz'

haplotype_vcf_template_url: 'ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr{chrom}.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz'

ref_genome_fasta_urls:
    - 'ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_27/GRCh37_mapping/GRCh37.primary_assembly.genome.fa.gz'
    - 'ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/phase2_reference_assembly_sequence/EBVt1.fa.gz'
    - 'ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5cs.fa.gz'
    - 'http://tools.thermofisher.com/downloads/ERCC92.fa'

ref_proteome_fasta_urls:
    - 'ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_27/GRCh37_mapping/gencode.v27lift37.pc_translations.fa.gz'
    
ref_transcriptome_fasta_urls:
    - 'ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_27/GRCh37_mapping/gencode.v27lift37.transcripts.fa.gz'
    - 'http://tools.thermofisher.com/downloads/ERCC92.fa'

ref_gene_annotations_gtf_urls:
    - 'ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_27/GRCh37_mapping/gencode.v27lift37.annotation.gtf.gz'
    - 'http://tools.thermofisher.com/downloads/ERCC92.gtf'

snpeff:
    db: 'GRCh37.75'
    url: 'http://downloads.sourceforge.net/project/snpeff/databases/v4_3/snpEff_v4_3_GRCh37.75.zip'